services:
  church-api-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=church
      - POSTGRESQL_PASSWORD=church_password
      - POSTGRESQL_DATABASE=church_api